; General pipeline settings
[General]
sample_name = my_experiment_run
start_stage = fastq
exit_stage = None ; Set to 'None' for full pipeline, or a stage name
output_directory = ./results
verbose_logging = True
force_overwrite = False ; Set to True to overwrite existing output directories

; Input file paths
[InputFiles]
genome_fasta = /path/to/my_data/genome.fasta
genome_index = /path/to/my_data/genome_index_prefix ; Optional: if not provided, Hicberg will build it
forward_reads = /path/to/my_data/reads_R1.fastq.gz
reverse_reads = /path/to/my_data/reads_R2.fastq.gz
blacklist_regions = None ; Set to 'None' or leave blank if no blacklist file otherwise provide either a bed file or a list of coordinates coma separated using UCSC format.

; Alignment parameters
[Alignment]
aligner = bowtie2 ; 'bowtie2', 'bwa' or 'minimap2'
cpus = 8
sensitivity = very-sensitive ; presets: very-fast, fast, sensitive, very-sensitive
max_alignment = None ; Max alignments to report per read (int) or 'None' for unlimited
mapq = 35
read_type = short ; "sr", "map-pb", "map-hifi", "map-ont", "splice", "splice:hq", "asm5", "asm10", "ava-pb" or"ava-ont"

; Processing parameters
[Processing]
enzyme = DpnII,HinfI ; Comma-separated list for multiple enzymes (e.g., 'DpnII,HinfI')
circular_genome = ; e.g., 'chrM' if mitochondrial genome is circular, otherwise leave blank or 'None' (ChrM in our genome example)
rate = 1.0 ; Downsampling rate (float)
distance = 1000 ; Distance parameter (int) for omics mode
bins = 2000 ; Contact map resolution(int)
mode = standard ; 'full', 'standard', 'density', or 'omics'
kernel_size = 11 ; Kernel size for density calculation (int)
deviation = 0.5 ; Deviation for density calculation (float)